import fonts from './fonts';
import palettes, { OldAsphalt } from './palettes';
import * as utils from './utils';
import * as tabs from './tabs';

const theme = {
  palettes,
  fonts,
  utils,
  tabs,
  fontWeights: {
    regular: 400,
    medium: 500,
    bold: 700,
    heavy: 800,
  },
  colors: {
    Black: '#000000',
    White: '#FFFFFF',
    Mercury: '#E5E5E5',
    Bunting: '#0C1630',
    Woodsmoke: '#0C0D10',
    Gray: '#878787',
    Horizon: '#617EAD',
    ScienceBlue: '#0055CB',
    Alto: '#E1DFDF',
    AliceBlue: '#FAFDFF',
    CatskillWhite: '#EEF2F6',
    Chambray: '#325692',
    MineShaft: '#393939',
    BlackHaze: '#EEF0F0',
    AquaHaze: '#F8FAFB',
    Iron: '#E0E1E4',
    Heather: '#BABFCD',
    PigeonPost: '#A0B7DB',
    Waterloo: '#7B819B',
    Kidnapper: '#D3E2C6',
    Parsley: '#1F581D',
    PurpleHeart: '#5F3AC8',
    MoonRaker: '#E0D9F6',
    FunBlue: '#1E5BAF',
    Soltitude: '#E0EDFF',
    Cherrywood: '#66151A',
    Azalea: '#F6C7CA',
    RawUmber: '#6D5412',
    CreamBrulee: '#FFE6A5',
    Mischka: '#D7D9E1',
    Peppermint: '#EBF8EA',
    CarouselPink: '#FBE9EA',
    CadetBlue: '#B0B3C3',
    Rhino: '#2B3858',
    AthensGray: '#E8E8EF',
    Nepal: '#8B99BB',
    BrickRed: '#CC2A35',
    Alabaster: '#FCFCFC',
    Thunder: '#231F20',
    Apple: '#379A34',
    Jumbo: '#83848C',
    Tapestry: '#A95A72',
    Solitude: '#E6F1FF',
    MexicanRed: '#A3212A',
    BarleyWhite: '#FFF2D0',
    Picasso: '#FFF59E',
    CarrotOrange: '#F19120',
    DodgerBlue: '#4794FF',
    Cobalt: '#0044A2',
    Cornflower: '#99BBEA',
    LinkWater: '#E6ECF6',
    ForestGreen: '#2A7128',
    Deluge: '#8455A8',
    Amethyst: '#914CC8',
    FrenchLilac: '#F4E5F9',
    FairPink: '#FFEDEE',
    JacksonsPurple: '#1B3A86',
    Burgundy: '#94002D',
    Shark: '#181920',
    BreakerBay: '#5DA1A5',
    PattensBlue: '#D7ECFF',
    Eminence: '#603780',
    NavajoWhite: '#FFDBA5',
    SilverChalice: '#9E9E9E',
    Anzac: '#DF8F44',

    // Figma
    Headers: OldAsphalt.L90,
    Main: OldAsphalt.L80,
    Notes: OldAsphalt.main,
    Inactive: OldAsphalt.L40,
    ControlOutline: OldAsphalt.L20,
    Separators: OldAsphalt.L20,
    PageBackground: OldAsphalt.L10,

    // Custom
    ContentBackground: '#E5E5E5',
    MenuBackground: '#FFFFFF',
    BlockBackground: '#FFFFFF',
    Whisper: '#F4F3F8',
  },
  sizes: {
    minDocumentHeight: 500,
    topMenuHeight: 60,
    footerHeight: 32,
    breadcrumbsBlockHeight: 44,
  },
  linkSizes: {
    small: {
      fontWeight: '600',
      fontVariant: 'h6',
    },
    medium: {
      fontWeight: '700',
      fontVariant: 'h5',
    },
    large: {
      fontWeight: '700',
      fontVariant: 'h4',
    },
  },
  shadows: {
    Empire: '0px 1px 2px rgba(0, 0, 0, 0.1)',
    Taipei: '0px 2px 4px rgba(0, 0, 0, 0.1)',
    Tokyo: '0px 4px 8px rgba(0, 0, 0, 0.1)',
    Khalifa: '0px 8px 12px rgba(0, 0, 0, 0.1)',
  },
};

export default theme;
